# Generated by Django 2.2.1 on 2019-05-21 08:19

import dashboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_no', models.IntegerField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_no', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('customer_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('customer_market_in', models.BooleanField(default=False)),
                ('customer_ratings', djongo.models.fields.EmbeddedModelField(model_container=dashboard.models.ratings, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('product_class', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtime_no', models.IntegerField()),
                ('productname', models.CharField(max_length=128)),
                ('titlename', models.CharField(max_length=128)),
                ('portalsite', models.CharField(max_length=128)),
                ('ranking', models.IntegerField(default=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_now', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Camera')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product'),
        ),
    ]
