# Generated by Django 2.2.1 on 2019-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtime',
            name='id',
        ),
        migrations.AlterField(
            model_name='realtime',
            name='realtime_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
