# Generated by Django 2.2.1 on 2019-05-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190521_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtime',
        ),
    ]
