# Generated by Django 2.2.1 on 2019-05-21 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_realtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('realtime_no', models.IntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=128)),
                ('titlename', models.CharField(max_length=128)),
                ('portalsite', models.CharField(max_length=128)),
                ('ranking', models.IntegerField(default=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
